export const FETCH_CHAMPION_MASTERY = 'FETCH_CHAMPION_MASTERY';

export const FETCH_GITHUB_ERROR = 'FETCH_GITHUB_ERROR';
export const FETCH_GITHUB_INFO = 'FETCH_GITHUB_INFO';

export const FETCH_SUMMONER_ERROR = 'FETCH_SUMMONER_ERROR';
export const FETCH_SUMMONER_INFO = 'FETCH_SUMMONER_INFO';
