// Riot
export const GET_CHAMPION_MASTERY = 'GET_CHAMPION_MASTERY';
export const GET_INFO_FROM_LOCAL_STORAGE = 'GET_INFO_FROM_LOCAL_STORAGE';
export const GET_SUMMONER_INFO = 'GET_SUMMONER_INFO';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
